services:
  s3-uploader:
    build:
      context: .
      target: final
      args:
        - UID=1001
      cache_from:
        - ghcr.io/recorder-moe/s3-uploader:cache
      cache_to:
        - type=inline
    environment:
      - S3_ENDPOINT=https://your-s3-endpoint
      - S3_ACCESS_KEY=your-s3-access-key
      - S3_SECRET_KEY=your-s3-secret-key
      - DESTINATION_BUCKET=your-bucket
      - DESTINATION_DIRECTORY=videos
    volumes:
      - /path/to/local/folder:/sharedvolume
    command: "keyword-of-the-filename"
